name: supnews
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  mobx: ^0.1.4
  flutter_mobx: ^0.1.3
  provider: ^2.0.0+1
  url_launcher: ^5.0.2
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.2
  share: ^0.6.1+1
  intl: ^0.15.8
  hnpwa_client: ^1.0.0
  flutter_statusbarcolor: ^0.2.0
  async:

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^0.1.3
  build_runner: ^1.4.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Medium.ttf
          weight: 500